import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from src.evaluation import get_failure_threshold


def plot_distribution_separation(df):
    """
    Génère un plot de séparation densité 1x4 haute qualité pour papier.

    Args:
        df: DataFrame contenant les scores et labels
    """
    # --- 1. CONFIGURATION ESTHÉTIQUE ---
    sns.set_context("paper", font_scale=1.4)
    sns.set_style("ticks")

    colors = sns.color_palette("colorblind")
    c_correct = colors[0]
    c_error = colors[1]

    NAME_MAPPING = {
        "score_cali": "CALI (Ours)",
        "score_softmax": "MSP (Baseline)",
        "score_energy": "Energy Score",
        "score_confidnet": "ConfidNet",
        "deep_ensemble_scores": "Deep Ensemble",
        "score_trust": "Trust Score",
        "score_mcdropout": "MC Dropout",
    }

    # --- 2. PRÉPARATION DU CANVAS ---
    fig, axes = plt.subplots(2, 4, figsize=(15, 6), sharex=True, sharey=False)

    is_correct = df["gold_label"] == df["predicted_label"]

    for i, col in enumerate(NAME_MAPPING.keys()):
        row = 0 if i < 4 else 1
        col_idx = i if i < 4 else i - 4
        ax = axes[row, col_idx]

        scores_correct = df.loc[is_correct, col]
        scores_error = df.loc[~is_correct, col]

        sns.kdeplot(
            scores_error,
            fill=True,
            color=c_error,
            alpha=0.3,
            linewidth=2,
            label="Error",
            ax=ax,
            clip=(0, 1),
            bw_adjust=1.2,
        )
        sns.kdeplot(
            scores_correct,
            fill=True,
            color=c_correct,
            alpha=0.3,
            linewidth=2,
            label="Correct",
            ax=ax,
            clip=(0, 1),
            bw_adjust=1.2,
        )

        display_name = NAME_MAPPING.get(col, col)
        ax.set_title(display_name, fontsize=16, fontweight="bold", pad=10)
        ax.set_xlim(0, 1.05)
        ax.set_xlabel("Confidence", fontsize=14)

        if i == 0:
            ax.set_ylabel("Density", fontsize=14)
            ax.legend(
                loc="upper left", ncol=1, frameon=True, fontsize=12, edgecolor="black"
            )
        else:
            ax.set_ylabel("")
            if ax.get_legend():
                ax.get_legend().remove()

    fig.delaxes(axes[1, 3])

    plt.tight_layout()
    sns.despine(offset=10, trim=True)
    plt.show()


def plot_risk_increase(
    seed: int = 0, deep_ensemble_seeds: list = [0, 1, 2, 3, 42], delta: float = 0.05
) -> None:
    """Plot local operational robustness curves for all available methods.

    The function loads the per-seed CSV generated by
    `save_failure_threshold`, filters rows for one `delta`, then plots the
    mean risk increase curve (with sampled error bars) for each method.

    Args:
        seed: Seed identifier used in the saved CSV filename.
        deep_ensemble_seeds: List of seeds for deep ensemble methods.
        delta: Perturbation ratio to visualize (value of the `Delta` column).

    Raises:
        FileNotFoundError: If the CSV file for `seed` does not exist.
        KeyError: If required columns are missing in the CSV.
        ValueError: If no rows match `delta` or no plottable data is available.
    """
    # If you want a special jitter, add the delta value in the call of save_failure_threshold. Example: save_failure_threshold(seed=0, delta=0.28)
    # deltas for [0.01, 0.02, 0.05, 0.1, 0.15, 0.2] are already computed in the CSV
    df = get_failure_threshold(
        seed=seed, deep_ensemble_seeds=deep_ensemble_seeds, delta=delta
    )

    def parse_numpy_string(value: object) -> np.ndarray:
        if isinstance(value, np.ndarray):
            return value.astype(float)
        if value is None:
            return np.array([], dtype=float)
        if isinstance(value, (float, np.floating)) and np.isnan(value):
            return np.array([], dtype=float)
        cleaned = str(value).replace("[", " ").replace("]", " ").replace("\n", " ")
        return np.fromstring(cleaned, sep=" ")

    sns.set_context("paper", font_scale=1.4)
    sns.set_style("ticks")

    method_colors = {
        "score_cali": "#F26619",
        "deep_ensemble_scores": "#FBCE9E",
        "score_mcdropout": "#944931",
        "score_energy": "#2F4558",
        "score_trust": "#335F8A",
        "score_confidnet": "#55D5E0",
        "score_softmax": "#95a5a6",
    }

    name_mapping = {
        "score_cali": "CALI (Ours)",
        "score_softmax": "MSP",
        "score_energy": "Energy Score",
        "score_confidnet": "ConfidNet",
        "deep_ensemble_scores": "Deep Ensemble",
        "score_trust": "Trust Score",
        "score_mcdropout": "MC Dropout",
    }

    methods_to_plot = df["Method"].dropna().unique()
    markers = ["o", "s", "^", "D", "v", "<", ">", "P", "X", "*"]
    _, ax = plt.subplots(figsize=(17, 5))

    plotted_count = 0
    for i, method in enumerate(methods_to_plot):
        df_method = df[df["Method"] == method]
        degradations = [
            parse_numpy_string(v) for v in df_method["Risk Increase"].values
        ]
        degradations = [arr for arr in degradations if arr.size > 0]
        if not degradations:
            continue

        thresholds = parse_numpy_string(df_method["Test Thresholds"].iloc[0])
        if thresholds.size == 0:
            continue

        min_len = min(min(arr.size for arr in degradations), thresholds.size)
        if min_len < 2:
            continue

        all_degradations = np.stack([arr[:min_len] for arr in degradations])
        tau_star = float(df_method["Tau Star"].iloc[0])
        x_axis = thresholds[:min_len] - tau_star

        mean_y = np.mean(all_degradations, axis=0)
        std_y = np.std(all_degradations, axis=0)
        mean_ari = float(df_method["ARI"].mean())
        label_txt = f"{name_mapping.get(method, method)} (ARI={mean_ari * 100:.4f}%)"

        line = ax.plot(
            x_axis,
            mean_y,
            color=method_colors.get(method),
            linewidth=3,
            label=label_txt,
            alpha=0.9,
        )

        sampled_points = min(8, min_len)
        indices = np.linspace(0, min_len - 1, sampled_points, dtype=int)

        ax.errorbar(
            x_axis[indices],
            mean_y[indices],
            yerr=std_y[indices],
            fmt="none",
            ecolor=line[0].get_color(),
            capsize=3,
            alpha=0.7,
        )

        ax.scatter(
            x_axis[indices],
            mean_y[indices],
            color=line[0].get_color(),
            marker=markers[i % len(markers)],
            s=50,
            zorder=3,
            edgecolors="white",
            linewidths=0.5,
        )
        plotted_count += 1

    if plotted_count == 0:
        raise ValueError("No valid curves could be plotted from the selected data.")

    ax.set_xlabel(
        f"Threshold Perturbation (τ ± {delta * 100:.0f}%)",
        fontsize=15,
        fontweight="bold",
    )
    ax.set_ylabel("Risk Increase", fontsize=15, fontweight="bold")

    ax.axvline(0, color="black", linestyle="--", alpha=0.4)
    ax.axhline(0, color="black", linestyle="--", alpha=0.4)

    if delta > 0:
        ax.set_xlim(-delta, delta)
        ax.set_xticks([-delta, -delta / 2, 0, delta / 2, delta])

    ax.set_ylim(-0.02, 0.6)

    legend = ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.18),
        fontsize=13,
        frameon=True,
        ncol=4,
    )
    for i, handle in enumerate(getattr(legend, "legend_handles", [])):
        if hasattr(handle, "set_marker"):
            handle.set_marker(markers[i % len(markers)])
        if hasattr(handle, "set_markersize"):
            handle.set_markersize(5)

    sns.despine(trim=True)
    plt.grid(True, linestyle=":")
    plt.tight_layout(rect=(0.0, 0.0, 1.0, 1.0))
    plt.show()
